module.exports = {
  indices: {
    status: 2,
    fileName: 3,
    gDriveFolderId: 5,
    jobNumber: 6,
    inspectionName: 9,
    inspectionType: 11,
    site: 12,
    totalScorePercentage: 13,
    inspectionResult: 14,
    notes: 16,
    kitPartNumber: 17,
    serialSeqNumber: 18,
    submittedBy: 19,
    submissionDate: 20,
    totalQuestions: 22,
    question1: 24,
  },
  id: "1MMhENQNeBaf9AZr7wfKtOvOZf_mBKh--BEXDv7bvh-Q",
};
